<a href="https://colab.research.google.com/github/smartinternz02/SI-GuidedProject-580786-1694703095/blob/main/asgn4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

#Data pre-processing

Loading dataset

In [66]:
df=pd.read_csv("/content/HR-Employee-Attrition.csv")
df

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

In [67]:
df.shape

(1470, 35)

Checking for null values

In [68]:
df.isnull().any()

Age                         False
Attrition                   False
BusinessTravel              False
DailyRate                   False
Department                  False
DistanceFromHome            False
Education                   False
EducationField              False
EmployeeCount               False
EmployeeNumber              False
EnvironmentSatisfaction     False
Gender                      False
HourlyRate                  False
JobInvolvement              False
JobLevel                    False
JobRole                     False
JobSatisfaction             False
MaritalStatus               False
MonthlyIncome               False
MonthlyRate                 False
NumCompaniesWorked          False
Over18                      False
OverTime                    False
PercentSalaryHike           False
PerformanceRating           False
RelationshipSatisfaction    False
StandardHours               False
StockOptionLevel            False
TotalWorkingYears           False
TrainingTimesL

Checking for dummies

In [69]:
data = pd.get_dummies(df, columns=['TotalWorkingYears'])
data

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  TotalWorkingYears_30 TotalWorkingYears_31  \
0                  1  ...                     0                    0   
1                  2  ...                     0                    0   
2                  4  ...                     0                    0   
3                  5  ...                     0                    0   
4                  7  ...                     0                    0   
...              ...  ...                   ...                  ...   
1465            2061  ...                     0                    0   
1466            2062  ...                     0                    0   
1467            2064  ...                     0                    0   
1468            2065  ...                     0                    0   
1469            2068  ...                     0                    0   

      TotalWorkingYears_32  TotalWorkingYears_33  TotalWorkingYears_34  \
0                        0                     0                     0   
1                        0                     0                     0   
2                        0                     0                     0   
3                        0                     0                     0   
4                        0                     0                     0   
...                    ...                   ...                   ...   
1465                     0                     0                     0   
1466                     0                     0                     0   
1467                     0                     0                     0   
1468                     0                     0                     0   
1469                     0                     0                     0   

     TotalWorkingYears_35  TotalWorkingYears_36 TotalWorkingYears_37  \
0                       0                     0                    0   
1                       0                     0                    0   
2                       0                     0                    0   
3                       0                     0                    0   
4                       0                     0                    0   
...                   ...                   ...                  ...   
1465              

Label Encoding

In [70]:
data['encoded_column'] = data['YearsAtCompany'].astype('category').cat.codes
print(data.head())

   Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  TotalWorkingYears_31 TotalWorkingYears_32  TotalWorkingYears_33  \

Min-Max Scaling (Normalization)

In [71]:
scaler = MinMaxScaler()
X_minmax = scaler.fit_transform(data[['WorkLifeBalance', 'TrainingTimesLastYear']])
X_minmax

array([[0.        , 0.        ],
       [0.66666667, 0.5       ],
       [0.66666667, 0.5       ],
       ...,
       [0.66666667, 0.        ],
       [0.33333333, 0.5       ],
       [1.        , 0.5       ]])

Standardization (Z-score Scaling)

In [72]:
scaler = StandardScaler()
X_stand = scaler.fit_transform(data[['WorkLifeBalance', 'TrainingTimesLastYear']])
X_stand

array([[-2.49382042, -2.17198183],
       [ 0.33809616,  0.15570708],
       [ 0.33809616,  0.15570708],
       ...,
       [ 0.33809616, -2.17198183],
       [-1.07786213,  0.15570708],
       [ 1.75405446,  0.15570708]])

Data splitting

In [73]:
X = data.drop('YearsWithCurrManager', axis=1)  # Features
y = data['YearsWithCurrManager']  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [74]:
X_train

Age Attrition     BusinessTravel  DailyRate              Department  \
1097   24        No      Travel_Rarely        350  Research & Development   
727    18        No         Non-Travel        287  Research & Development   
254    29        No      Travel_Rarely       1247                   Sales   
1175   39        No      Travel_Rarely        492  Research & Development   
1341   31        No      Travel_Rarely        311  Research & Development   
...   ...       ...                ...        ...                     ...   
1130   35        No      Travel_Rarely        750  Research & Development   
1294   41        No      Travel_Rarely        447  Research & Development   
860    22       Yes  Travel_Frequently       1256  Research & Development   
1459   29        No      Travel_Rarely       1378  Research & Development   
1126   50        No      Travel_Rarely        264                   Sales   

      DistanceFromHome  Education    EducationField  EmployeeCount  \
1097                21          2  Technical Degree              1   
727                  5          2     Life Sciences              1   
254                 20          2         Marketing              1   
1175                12          3           Medical              1   
1341                20          3     Life Sciences              1   
...                ...        ...               ...            ...   
1130                28          3     Life Sciences              1   
1294                 5          3     Life Sciences              1   
860                  3          4     Life Sciences              1   
1459                13          2             Other              1   
1126                 9          3         Marketing              1   

      EmployeeNumber  ...  TotalWorkingYears_31 TotalWorkingYears_32  \
1097            1551  ...                     0                    0   
727             1012  ...                     0                    0   
254              349  ...                     0                    0   
1175            1654  ...                     0                    0   
1341            1881  ...                     0                    0   
...              ...  ...                   ...                  ...   
1130            1596  ...                     0                    0   
1294            1814  ...                     0                    0   
860             1203  ...                     0                    0   
1459            2053  ...                     0                    0   
1126            1591  ...                     0                    0   

      TotalWorkingYears_33  TotalWorkingYears_34  TotalWorkingYears_35  \
1097                     0                     0                     0   
727                      0                     0                     0   
254                      0                     0                     0   
1175                     0                     0                     0   
1341                     0                     0                     0   
...                    ...                   ...                   ...   
1130                     0                     0                     0   
1294                     0                     0                     0   
860                      0                     0                     0   
1459                     0                     0                     0   
1126                     0                     0                     0   

     TotalWorkingYears_36  TotalWorkingYears_37 TotalWorkingYears_38  \
1097                    0                     0                    0   
727                     0                     0                    0   
254                     0                     0                    0   
1175                    0                     0                    0   
1341                    0                     0                    0   
...                   ...                   ...       

In [75]:
X_test

Age Attrition BusinessTravel  DailyRate              Department  \
1041   28        No  Travel_Rarely        866                   Sales   
184    53        No  Travel_Rarely       1084  Research & Development   
1222   24       Yes  Travel_Rarely        240         Human Resources   
67     45        No  Travel_Rarely       1339  Research & Development   
220    36        No  Travel_Rarely       1396  Research & Development   
...   ...       ...            ...        ...                     ...   
567    34        No  Travel_Rarely        304                   Sales   
560    34        No  Travel_Rarely        167  Research & Development   
945    50        No  Travel_Rarely       1322  Research & Development   
522    37        No  Travel_Rarely       1225  Research & Development   
651    47        No  Travel_Rarely        249                   Sales   

      DistanceFromHome  Education   EducationField  EmployeeCount  \
1041                 5          3          Medical              1   
184                 13          2          Medical              1   
1222                22          1  Human Resources              1   
67                   7          3    Life Sciences              1   
220                  5          2    Life Sciences              1   
...                ...        ...              ...            ...   
567                  2          3            Other              1   
560                  8          5    Life Sciences              1   
945                 28          3    Life Sciences              1   
522                 10          2    Life Sciences              1   
651                  2          2        Marketing              1   

      EmployeeNumber  ...  TotalWorkingYears_31 TotalWorkingYears_32  \
1041            1469  ...                     0                    0   
184              250  ...                     0                    0   
1222            1714  ...                     0                    0   
67                86  ...                     0                    0   
220              304  ...                     0                    0   
...              ...  ...                   ...                  ...   
567              786  ...                     0                    0   
560              775  ...                     0                    0   
945             1317  ...                     0                    0   
522              715  ...                     0                    0   
651              903  ...                     0                    0   

      TotalWorkingYears_33  TotalWorkingYears_34  TotalWorkingYears_35  \
1041                     0                     0                     0   
184                      0                     0                     0   
1222                     0                     0                     0   
67                       0                     0                     0   
220                      0                     0                     0   
...                    ...                   ...                   ...   
567                      0                     0                     0   
560                      0                     0                     0   
945                      0                     0                     0   
522                      0                     0                     0   
651                      0                     0                     0   

     TotalWorkingYears_36  TotalWorkingYears_37 TotalWorkingYears_38  \
1041                    0                     0                    0   
184                     0                     0                    0   
1222                    0                     0                    0   
67                      0                     0                    0   
220                     0                     0                    0   
...                   ...                   ...                  ...   
567                     0                 

In [76]:
y_train

1097    0
727     0
254     2
1175    0
1341    2
       ..
1130    8
1294    2
860     0
1459    3
1126    0
Name: YearsWithCurrManager, Length: 1176, dtype: int64

In [77]:
y_test

1041    3
184     3
1222    0
67      0
220     7
       ..
567     4
560     0
945     2
522     0
651     7
Name: YearsWithCurrManager, Length: 294, dtype: int64

#Logistic regression

In [78]:
X = data.drop('YearsSinceLastPromotion', axis=1)
y = data['YearsSinceLastPromotion']
X = pd.get_dummies(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Create and train Logestic Regression Model

In [79]:
model = LogisticRegression()
model.fit(X_train, y_train)
model

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

Predict test set

In [80]:
y_prdt = model.predict(X_test)
y_prdt

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 15,
        0, 11,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,
        0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,
        0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 15,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,
        0,  0,  0,  0,  0, 15,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

Evaluate the model

In [81]:
acry = accuracy_score(y_test, y_prdt)
print("Logistic Regression Model Accuracy:", acry)

Logistic Regression Model Accuracy: 0.35034013605442177


Classification model

In [82]:
print("Classification Report:")
print(classification_report(y_test, y_prdt))

Classification Report:
              precision    recall  f1-score   support

           0       0.37      0.95      0.53       107
           1       0.17      0.01      0.02        75
           2       0.00      0.00      0.00        25
           3       0.00      0.00      0.00        12
           4       0.00      0.00      0.00        15
           5       0.00      0.00      0.00        12
           6       0.00      0.00      0.00         6
           7       0.00      0.00      0.00        17
           8       0.00      0.00      0.00         2
           9       0.00      0.00      0.00         2
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         7
          12       0.00      0.00      0.00         2
          13       0.00      0.00      0.00         3
          14       0.00      0.00      0.00         2
          15       0.00      0.00      0.00         6

    accuracy                           0.35       294
   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy

In [83]:
accuracy = accuracy_score(y_test, y_prdt)
print("Accuracy:", accuracy)

Accuracy: 0.35034013605442177


Precision

In [84]:
# Micro-averaging
precision_micro = precision_score(y_test, y_prdt, average='micro')
print("Micro-averaged Precision:", precision_micro)

# Macro-averaging
precision_macro = precision_score(y_test, y_prdt, average='macro')
print("Macro-averaged Precision:", precision_macro)

# Weighted-averaging
precision_weighted = precision_score(y_test, y_prdt, average='weighted')
print("Weighted-averaged Precision:", precision_weighted)

Micro-averaged Precision: 0.35034013605442177
Macro-averaged Precision: 0.03326612903225806
Weighted-averaged Precision: 0.17557237948943016


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Recall

In [85]:
# Recall for each class
recall_per_class = recall_score(y_test, y_prdt, average=None)

# Macro-averaged recall
recall_macro = recall_score(y_test, y_prdt, average='macro')

# Weighted-averaged recall
recall_weighted = recall_score(y_test, y_prdt, average='weighted')

print("Recall for each class:", recall_per_class)
print("Macro-averaged Recall:", recall_macro)
print("Weighted-averaged Recall:", recall_weighted)

Recall for each class: [0.95327103 0.01333333 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]
Macro-averaged Recall: 0.06041277258566978
Weighted-averaged Recall: 0.35034013605442177


F1 score

In [86]:
# Calculate F1-score for each class
f1_per_class = f1_score(y_test, y_prdt, average=None)

# Calculate macro-averaged F1-score
f1_macro = f1_score(y_test, y_prdt, average='macro')

# Calculate weighted-averaged F1-score
f1_weighted = f1_score(y_test, y_prdt, average='weighted')

print("F1 Score for each class:", f1_per_class)
print("Macro-averaged F1 Score:", f1_macro)
print("Weighted-averaged F1 Score:", f1_weighted)

F1 Score for each class: [0.52849741 0.02469136 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]
Macro-averaged F1 Score: 0.034574297959444764
Weighted-averaged F1 Score: 0.19864311105367116


Confusion matrix

In [87]:
conf_matrix = confusion_matrix(y_test, y_prdt)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[102   4   0   0   0   0   0   0   0   0   0   0   0   0   0   1]
 [ 73   1   0   0   0   0   0   0   0   0   0   1   0   0   0   0]
 [ 23   0   0   0   2   0   0   0   0   0   0   0   0   0   0   0]
 [ 12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 14   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0]
 [ 12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  6   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 16   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  5   0   0   0   0   0   0   0   0   0   0   0   0   0   0   2]
 [  1   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0]
 [  3   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0   0   